// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk5g4RaBwMfGbqCfRSi75LPbRCFVUOlGk',
    appId: '1:979220825797:web:f652aa52313cd13bce92ac',
    messagingSenderId: '979220825797',
    projectId: 'medilens-79a2c',
    authDomain: 'medilens-79a2c.firebaseapp.com',
    storageBucket: 'medilens-79a2c.firebasestorage.app',
    measurementId: 'G-B5K3KSEFMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzUUsPMEV56lB9ilTE0hui6_SxddruU6s',
    appId: '1:979220825797:android:5b6ee32dd61f813cce92ac',
    messagingSenderId: '979220825797',
    projectId: 'medilens-79a2c',
    storageBucket: 'medilens-79a2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbBbSDECwdoylBr4O7XZ13MuNUTeJ-lXk',
    appId: '1:979220825797:ios:30d59a07d76efdcece92ac',
    messagingSenderId: '979220825797',
    projectId: 'medilens-79a2c',
    storageBucket: 'medilens-79a2c.firebasestorage.app',
    iosBundleId: 'com.example.medilens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbBbSDECwdoylBr4O7XZ13MuNUTeJ-lXk',
    appId: '1:979220825797:ios:30d59a07d76efdcece92ac',
    messagingSenderId: '979220825797',
    projectId: 'medilens-79a2c',
    storageBucket: 'medilens-79a2c.firebasestorage.app',
    iosBundleId: 'com.example.medilens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk5g4RaBwMfGbqCfRSi75LPbRCFVUOlGk',
    appId: '1:979220825797:web:e72ae5131385be81ce92ac',
    messagingSenderId: '979220825797',
    projectId: 'medilens-79a2c',
    authDomain: 'medilens-79a2c.firebaseapp.com',
    storageBucket: 'medilens-79a2c.firebasestorage.app',
    measurementId: 'G-95R7ER5KZH',
  );
}
